In [2]:
import numpy as np

In [6]:
x=np.zeros((2,3,4))
print(x)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [7]:
x.shape

(2, 3, 4)

In [8]:
x.ndim

3

In [9]:
x.size

24

In [10]:
x.dtype

dtype('float64')