In [2]:
import numpy as np

In [2]:
x=np.zeros([3,8,8,5])

In [3]:
x

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],



In [3]:
np.full((4,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [4]:
np.full(4,8)

array([8, 8, 8, 8])

In [6]:
np.full((3,5),"a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [7]:
np.full((2,5), 9.4)

array([[9.4, 9.4, 9.4, 9.4, 9.4],
       [9.4, 9.4, 9.4, 9.4, 9.4]])

In [8]:
np.full((2,5), 9.4, dtype="str")

array([['9', '9', '9', '9', '9'],
       ['9', '9', '9', '9', '9']], dtype='<U1')

In [11]:
x=np.array([1,3.7,6,54.345])

In [12]:
x

array([ 1.   ,  3.7  ,  6.   , 54.345])

In [13]:
x=np.array([1,3.7,6,54.345], dtype="int32")

In [14]:
x

array([ 1,  3,  6, 54], dtype=int32)

In [15]:
x=np.array(["a"], dtype="int32")

ValueError: invalid literal for int() with base 10: 'a'

In [16]:
x=np.array(["8"], dtype="int32")

In [17]:
x

array([8], dtype=int32)