In [19]:
import numpy as np

In [4]:
np.arange(0,8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
np.arange(0,8,2)

array([0, 2, 4, 6])

In [11]:
np.arange(8,0,-2)

array([8, 6, 4, 2])

In [12]:
np.arange(13,1,-3)

array([13, 10,  7,  4])

In [14]:
np.arange(13,4,-3)

array([13, 10,  7])

In [15]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [16]:
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [23]:
np.linspace(1, 2, num=3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

In [24]:
np.random.normal(0,1,(4,5))

array([[-0.55145882,  1.05720496, -0.80542211, -0.12865282,  0.34581578],
       [-0.27592003,  0.68382331,  2.3599667 ,  0.90721168,  1.45813472],
       [ 0.13820172,  0.28465965,  1.95138704, -0.04754834, -1.11783839],
       [-0.54217872, -1.06218122, -0.25997193,  0.8788076 , -0.79783532]])

In [25]:
np.random.normal(0,100,(4,5))

array([[ 111.62215481, -101.27086963, -108.44406841,   16.50810852,
         115.80344037],
       [ -44.31932375,  -57.47742107, -226.62180482,    0.34725199,
          80.43330569],
       [-157.58636636,  116.677666  ,  -62.76728143,  139.72086428,
         128.1197059 ],
       [-135.17054068,  159.39775267,   45.37774917,  -28.82577833,
         163.99238522]])

In [26]:
np.random.normal(10,1,(4,5))

array([[ 9.30519417, 10.27578977,  8.55445029, 10.17250993,  9.58383001],
       [ 8.82286791, 10.57119216, 10.99180665, 11.41147884,  9.82806906],
       [ 9.01087307,  9.92116793,  9.94448074,  9.15193089,  9.02201786],
       [10.87398303,  8.06550616,  9.93417749, 10.07657684, 10.9061442 ]])

In [27]:
np.random.normal(10,100,(4,5))

array([[  85.33929438,   62.94535564,  -59.77469637,   77.80786692,
         -48.45245109],
       [  -4.91990526,   98.15319253,   43.71863568, -104.58576143,
        -121.03100461],
       [-146.21107322, -122.46990636,  -43.91105187,    4.5913154 ,
           6.5585002 ],
       [  12.82690043,  114.4778104 ,   67.85245714,   27.51375529,
           3.02989378]])

In [29]:
np.random.randint(5,15,(3,3))

array([[10,  5,  7],
       [14, 13, 14],
       [ 7,  6,  6]], dtype=int32)

In [30]:
np.random.randint(5,15,(3,3,2))

array([[[ 5,  7],
        [14, 13],
        [ 8,  7]],

       [[11, 13],
        [12,  6],
        [ 8, 10]],

       [[ 6, 10],
        [10, 10],
        [11,  7]]], dtype=int32)

In [32]:
np.random.randint(1,2)

1

In [43]:
d={}
for _ in range(20000):
    val=np.random.randint(5,15)
    if val not in d:
        d[val]=1
    else:
        d[val]+=1    

In [44]:
d

{14: 2022,
 9: 2019,
 6: 2009,
 5: 1998,
 11: 1894,
 8: 1998,
 13: 1892,
 7: 2091,
 12: 2010,
 10: 2067}

In [45]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [48]:
x=np.array([1,2,3])
y=np.array([33,44,55])
x*y

array([ 33,  88, 165])

In [49]:
z=np.array([1,2,3,4])
q=np.array([33,44,55])
z*q

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [50]:
x+y

array([34, 46, 58])